apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "vdojava.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vdojava.name" . }}
    helm.sh/chart: {{ include "vdojava.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vdojava.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vdojava.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: vdojavaport
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: CONFIG_STORE_BASE_URL
              value: {{ .Values.environmentVars.configStoreBaseUrl }}
            - name: CONFIG_STORE_DICTIONARY_NAME
              value: {{ .Values.environmentVars.configStoreDictionaryName }}
            - name: IDENTITY_USERNAME
              value: {{ .Values.environmentVars.identityUsername }}
            - name: IDENTITY_PASSWORD
              value: "{{ .Values.environmentVars.identityPassword }}"
            - name: IDENTITY_BASE_URL
              value: {{ .Values.environmentVars.identityBaseUrl }}
          livenessProbe:
            tcpSocket:
              port: vdojavaport
            initialDelaySeconds: 300
          readinessProbe:
            tcpSocket:
              port: vdojavaport
            initialDelaySeconds: 300
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
